# Generated by Django 3.2.25 on 2024-05-31 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=25)),
                ('age_type', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('survival_probability', models.FloatField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('total_burned_area', models.FloatField(blank=True, null=True)),
                ('is_inhalation', models.BooleanField(choices=[('Y', 'YES'), ('N', 'NO')])),
                ('weight', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useroftbsa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tbsa_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('image_type', models.CharField(max_length=10)),
                ('tbsa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tbsa_image', to='tbsa.tbsa')),
            ],
        ),
    ]
