# Generated by Django 3.2.25 on 2024-05-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbsa',
            name='is_inhalation',
            field=models.BooleanField(),
        ),
    ]
