# Generated by Django 4.2.13 on 2024-07-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbsa', '0003_auto_20240601_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbsa',
            name='tbsa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
