# Generated by Django 3.2.25 on 2024-06-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstAidsProcedure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstaidsprocedure',
            name='procedure_for_degree',
            field=models.CharField(max_length=50),
        ),
    ]
